name: cronometro_vp
description: "Cronómetro para Vida Plena"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2  # Dependencia para guardar la configuración
  wakelock_plus: ^1.1.4       # Dependencia para mantener la pantalla encendida

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 # <-- La herramienta mágica para los iconos

flutter:
  uses-material-design: true
  
  fonts:
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf

# -------------------------------------------------------------------
# CONFIGURACIÓN PARA GENERAR EL ICONO NATIVO DE LA APP
# -------------------------------------------------------------------
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # La ruta de la imagen que me compartiste
  remove_alpha_ios: true                # iOS no permite transparencias en el icono